# Generated by Django 3.2.21 on 2023-11-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_booking_brand_contact_testemonial_user_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testemonial',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
