# Generated by Django 3.2.21 on 2023-11-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
