# Generated by Django 3.2.21 on 2023-11-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
